;Subtract first 10 element of reverse lucas series

[ORG 0x0100]

MOV AX, 76		;SETS FIRST VARIABLE REG TO 76
MOV BX, 47		;SETS FIRST VARIABLE REG TO 47
MOV CX, AX		;fOR STORING VALUE OF RESULT
SUB CX, BX		;OBTAIN THIRD TERM

MOV AX, BX		;PUTS BX IN AX ie 47
MOv BX, CX		;Puts cx in Bx ie 29
MOV CX, AX		;
SUB CX, BX		;OBTAINS FOURTH TERM

MOV AX, BX		;PUTS BX IN AX ie 47
MOv BX, CX		;Puts cx in Bx ie 29
MOV CX, AX		;
SUB CX, BX		;OBTAINS FOURTH TERM

MOV AX, BX		;PUTS BX IN AX ie 47
MOv BX, CX		;Puts cx in Bx ie 29
MOV CX, AX		;
SUB CX, BX		;OBTAINS FOURTH TERM

MOV AX, BX		;PUTS BX IN AX ie 47
MOv BX, CX		;Puts cx in Bx ie 29
MOV CX, AX		;
SUB CX, BX		;OBTAINS FOURTH TERM

MOV AX, BX		;PUTS BX IN AX ie 47
MOv BX, CX		;Puts cx in Bx ie 29
MOV CX, AX		;
SUB CX, BX		;OBTAINS FOURTH TERM

MOV AX, BX		;PUTS BX IN AX ie 47
MOv BX, CX		;Puts cx in Bx ie 29
MOV CX, AX		;
SUB CX, BX		;OBTAINS FOURTH TERM

MOV AX, BX		;PUTS BX IN AX ie 47
MOv BX, CX		;Puts cx in Bx ie 29
MOV CX, AX		;
SUB CX, BX		;OBTAINS FOURTH TERM

MOV AX, 0x4C00		;
INT 0X21		;